package pairwisetesting.service;
//Generated by MyEclipse

public interface IPairwiseTestingService {
	
	//获得Pairwise组合结果
	public String PariwiseTesting(String inputMetaParameter,String engineName);
	
}